### ISSUE TITLE
Namespace optimization

### ISSUE THREAD

**Issue by eranFirelfy** [stickleprojects/VSDropAssist#19]
When dragging an entity into my class 
it adds the full namespace. For example - Northwind.Models.Categories rather than Models.Categories
![2016-03-22_10h03_49](https://cloud.githubusercontent.com/assets/18003268/13946745/0a448e04-f01f-11e5-8ed9-74977b6037df.jpg)

**Comment by stickleprojects** [comment]
As agreed. this is fixed in the beta
