### ISSUE TITLE
Drop action is done in a new line

### ISSUE THREAD

**Issue by eranFirelfy** [stickleprojects/VSDropAssist#26]
In this example, I dropped the member to line 14 - it was created in line 15:
![2016-03-28_10h05_03](https://cloud.githubusercontent.com/assets/18003268/14072837/b2af1eae-f4cc-11e5-8cde-72810ac8b214.jpg)

Is this done intentionally?

**Comment by stickleprojects** [comment]
Hi
Yes this is intentional, however, I could make the drop smarter so that if
you're dropping onto a blank line already, it doesnt insert a new one
