### ISSUE TITLE
Inconsistency of the drop 

### ISSUE THREAD

**Issue by eranFirelfy** [stickleprojects/VSDropAssist#28]
This is the result of multiple drops:
![2016-03-28_10h12_15](https://cloud.githubusercontent.com/assets/18003268/14072946/ac8df684-f4cd-11e5-9e96-d76846e4e99a.jpg)

All the Greens are dropped with no keyboard support - OK.
All the Yellows are dropped with a Shift - note that 4 of them are "var [shortname]..."
Only the 5th one is as it should be.

**Comment by stickleprojects** [comment]
1. Green - fine
2. Yellow, see that the 3rd green line does not end with a ;, so is treated like a function by the editor, hence [Shift]+[Dropping a class]+[into a method] is working
3. Line above is a correct and complete c# line of code and the text editor recognises the previous method declaration (categories) as "finished", so [Shift] + [Dropping a class] + [outside a method] is working

No workarounds at this time, apart from ensuring code compiles before dragging and dropping

**Comment by stickleprojects** [comment]
Closing as expected VS behaviour for code that doesnt compile
