### ISSUE TITLE
Visual Studio 2015 - Drag variable with alt

### ISSUE THREAD

**Issue by vlellouche** [stickleprojects/VSDropAssist#34]
In previous version of DropAssist in VS2015, when we drag variable with alt, the result was

```cs
class_name.variable.Value = ;
```
With the new version, nothing happen

**Comment by stickleprojects** [comment]
Hi

Looks like the plug in is not registered correctly with your vs2015.
Suggest abort testing until that is resolved. There is a log file in your
roaming profile that might indicate a problem. I will locate the path this
evening and send you details of you could then send me a copy that would
help.
Many thanks

Kieron

On 22 Feb 2017 3:17 p.m., "vlellouche" <notifications@github.com> wrote:

In previous version of DropAssist in VS2015, when we drag variable with
alt, the result was

class_name.variable.Value = ;

With the new version, nothing happen

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FireflyMigration/VSDropAssist/issues/34>, or mute the
thread

**Comment by stickleprojects** [comment]
Hi,
Please can you send me the ActivityLog.xml file from:
C:\Users\[your pc username]\appdata\Roaming\Microsoft\VisualStudio\14.0

Or
Open the file by double-clicking on it and scroll down to the RED bit(s), and send me that:
(example below)
![image](https://cloud.githubusercontent.com/assets/11067183/23222630/72c02cda-f920-11e6-8db8-c9da8fb46cc8.png)

this will give me a reason/cause as to why the plugin isnt registered.
thanks

**Comment by vlellouche** [comment]
Hi Kieron, 

This is my log file of VS2015. Let me know if you need something else
![2017-02-23_13h22_21](https://cloud.githubusercontent.com/assets/24289222/23257144/34e187dc-f9cb-11e6-9d92-7d2e3f8adc04.png)
thanks you

**Comment by stickleprojects** [comment]
Hi
Ive installed the 1.5 version of the plugin on an instance of VS2015 community (after uninstalling my previous copy of 1.5). Can you try the attached please?
With class fields, ALT only really works when dropping into a function

[VSDropAssist.zip](https://github.com/FireflyMigration/VSDropAssist/files/801021/VSDropAssist.zip)

**Comment by vlellouche** [comment]
this version works on VS2015 Enterprise, I tested :
- Shift  + Drag : 
- Ctrl + Drag
- Alt + Drag

**Comment by stickleprojects** [comment]
Great. Shall I add this as the next 2015 realise?

**Comment by vlellouche** [comment]
but i want to test this version on VS2017 and i received this message  
![image](https://cloud.githubusercontent.com/assets/24289222/23339192/92c95774-fc25-11e6-92bb-5490c2881f5e.png)
Can you check why please

**Comment by stickleprojects** [comment]
The version attached in this thread is pre-2017 version, hence it wont work in 2017 (but should work in 2015 and prior). I will review the 2017 version and respond back

**Comment by noam-honig** [comment]
Let us know if we are going to have separate versions for 2015 and 2017

**Comment by stickleprojects** [comment]
Ok. Please find attached a version that works with vs2015 community and vs2017 community.
Also included is a matrix of the various combinations of keys, items-being-dragged and where-youre-dropping-them.
I believe this matrix is the same as the prior one, however, i did note that we were getting some ambiguous selections in the pre-2017 version.
I'd be happy to adjust to any matrix you supply

[VSDropAssist.2017.vsix.zip](https://github.com/FireflyMigration/VSDropAssist/files/802090/VSDropAssist.2017.vsix.zip)

**Comment by vlellouche** [comment]
Hi,
Thanks you for your matrix, it really helped me tor test correctly

This the result of test :

[Result_vsdropassist.xlsx](https://github.com/FireflyMigration/VSDropAssist/files/803134/Result_vsdropassist.xlsx)
