### ISSUE TITLE
Problem dropping into VS2017

### ISSUE THREAD

**Issue by stickleprojects** [stickleprojects/VSDropAssist#35]
Version 2017.4 will not drop correctly onto an application with a large MDI form

**Comment by stickleprojects** [comment]
Found lots of interesting VS2017 issues:
lightweight solution loading means that the view your drophandler is iniitialized with, might be replaced during the lifetime of the drop operation - solution, ensure a new drophandler is created on every request from visual studio (previusly, I cached it)
vs2017 allows for null namespaces on codemodel objects- something that we didnt see in vs2015
numerous timeout and operationwascancelled exceptions occur during a drag and drop operation whilst the solution is being loaded (!!)
Debug build attached that hopefully addresses the reported issue (which does appear to be linked to the lightweight solution loading)

[VSDropAssist.zip](https://github.com/FireflyMigration/VSDropAssist/files/863045/VSDropAssist.zip)

**Comment by vlellouche** [comment]
Hi Kieron,
it works now, you can release this version please.
Thanks you

**Comment by stickleprojects** [comment]
Great! thanks for your clear help diagnosing the issues
This has been released now
best regards
Kieron
